apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: app-limited
rules:
  - apiGroups: ["" ]
    resources: ["pods", "configmaps" ]
    verbs: ["get", "list", "watch" ]
