apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spspdeny
spec:
  crd:
    spec:
      names:
        kind: K8sPSPDeny
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spspdeny
        violation[{"msg": msg}] {
          input.review.object.spec.containers[_].securityContext.runAsNonRoot != true
          msg := "All containers must set runAsNonRoot=true in securityContext"
        }
