apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digicloset.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: digicloset-backend
  template:
    metadata:
      labels:
        app: digicloset-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
